# Generated by Django 3.2.8 on 2021-12-08 23:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catering_event',
            name='cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='catering_event',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='menu_item',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
